app = 'uptime-kuma-tailscale'
primary_region = 'sin'

[build]

[[mounts]]
source = 'appstate'
destination = '/app/data'

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
