# fly.toml app configuration file generated for uptime-kuma-tailscale-restless-sun-8096 on 2025-10-25T08:43:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uptime-kuma-tailscale-restless-sun-8096'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'appstate'
  destination = '/app/data'

# [http_service]
#   internal_port = 80
#   force_https = true
#   auto_stop_machines = 'off'
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
